### ISSUE TITLE
Make more reusabe

### ISSUE THREAD

**Issue by parmeetmaster** [islamdidarmd/flutter_adblocker_webview#11]
Hello bro,

You need to apply cache mechanism once the file is load by api it must be reused.Everytime user open webview you api is calling again ang again least provide additional parameter use like to cache loaded till that hours.

**Comment by islamdidarmd** [comment]
It's a good idea to cache the response till some period actually. Need to think more about how to implement this. If you have a proposal you can raise a PR. I will need some time to get back to it.

**Comment by islamdidarmd** [comment]
New version `1.1.0` has been published to pub dev which addresses this issue.

**Comment by parmeetmaster** [comment]
Kindly update documentation as well how to use this
