### ISSUE TITLE
add sites from easylist

### ISSUE THREAD

**Issue by nadveos** [islamdidarmd/flutter_adblocker_webview#12]
Enhancement required!!
Add sites blocked from easylist on github

**Comment by islamdidarmd** [comment]
Can you provide a link to the sites?

**Comment by nadveos** [comment]
https://easylist-downloads.adblockplus.org/easylist.txt it's used by all dablocker plugins and if possible add a prop to add customs urls

**Comment by nadveos** [comment]
> https://easylist-downloads.adblockplus.org/easylist.txt it's used by all dablocker plugins and if possible add a prop to add customs urls

u can see more in this repo

**Comment by nadveos** [comment]
new sites to add https://annulmentequitycereals.com
https://trk.myperfect2give.com
https://record.pba.betsson.bet.ar in block list
