### ISSUE TITLE
Option to load html string.

### ISSUE THREAD

**Issue by nicks258** [islamdidarmd/flutter_adblocker_webview#22]
Like other web view plugins, it should support the feature to load a webpage from HTML strings something from iframes and all.
@islamdidarmd

**Comment by islamdidarmd** [comment]
Hi @nicks258 , thank you for opening this issue. I should look into it 😄

**Comment by islamdidarmd** [comment]
Hi @nicks258 this feature should now be available on version 1.2.0.
