### ISSUE TITLE
Support for flutter_adblocker_webview as a plug-and-play solution for flutter_inappwebview

### ISSUE THREAD

**Issue by SethuSenthil** [islamdidarmd/flutter_adblocker_webview#6]
I would like to request support for integrating flutter_adblocker_webview as a simple plug-and-play solution for flutter_inappwebview.

Currently, many developers, including myself, have existing codebases that utilize flutter_inappwebview for embedding web content within Flutter applications. However, we would like to enhance our apps by incorporating adblocking functionality without having to completely rewrite our WebView implementation.

The flutter_adblocker_webview package provides excellent adblocking capabilities, which could greatly benefit developers who are already using flutter_inappwebview. It would be fantastic if we could seamlessly integrate flutter_adblocker_webview into our existing projects without the need for significant modifications.

By offering compatibility between flutter_inappwebview and flutter_adblocker_webview, developers could easily add adblocking functionality to their apps without sacrificing the stability and features provided by flutter_inappwebview. This integration would save us time, effort, and potential compatibility issues that might arise from migrating to a different WebView package.

Thank you for considering this integration request. I believe it would be a valuable addition to both flutter_inappwebview and flutter_adblocker_webview, enabling developers to enhance their applications with adblocking capabilities effortlessly. If you require any further information or have any questions, please let me know!

I will try opening pulls to implement this functionally!

**Comment by islamdidarmd** [comment]
@SethuSenthil I have not checked the possibility of integrating this. If you want to work on it that will be great 👍

**Comment by islamdidarmd** [comment]
Hi, could you manage to work on the said feature? If not, I will close this issue.
